# Generated by Django 4.2.7 on 2025-07-25 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('payment_method_code', models.CharField(choices=[('Card', 'Credit/Debit Card'), ('Mpesa', 'Mobile Money'), ('PayPal', 'PayPal'), ('Wallet', 'Internal Wallet')], max_length=20)),
                ('transaction_ref', models.CharField(blank=True, max_length=255)),
                ('payment_timestamp', models.DateTimeField(auto_now_add=True)),
                ('status_code', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Failed', 'Failed'), ('Refunded', 'Refunded')], max_length=20)),
                ('gateway_payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('_encrypted_card_last4', models.TextField(blank=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bookings.booking')),
            ],
            options={
                'db_table': 'payment',
            },
        ),
        migrations.CreateModel(
            name='PaymentGatewayConfig',
            fields=[
                ('config_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('gateway_type', models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('mpesa', 'M-Pesa'), ('java_spring', 'Java Spring Service')], max_length=20)),
                ('gateway_name', models.CharField(max_length=100)),
                ('endpoint_url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('config_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('_encrypted_api_key', models.TextField(blank=True)),
                ('_encrypted_secret_key', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentAuditLog',
            fields=[
                ('audit_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('CAPTURED', 'Payment Captured'), ('REFUNDED', 'Payment Refunded'), ('FAILED', 'Payment Failed'), ('CANCELLED', 'Payment Cancelled')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.TextField(blank=True)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('snapshot_json', models.JSONField(default=dict)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='payments.payment')),
                ('performed_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment_audit_log',
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['booking'], name='payment_booking_df08d9_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status_code'], name='payment_status__f13bdb_idx'),
        ),
    ]
