# Generated by Django 4.2.7 on 2025-07-25 14:42

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('venue_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('venue_name', models.CharField(max_length=255)),
                ('venue_type_code', models.CharField(choices=[('CoffeeShop', 'Coffee Shop'), ('Hotel', 'Hotel'), ('CoworkingHub', 'Coworking Hub')], max_length=20)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=2)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('wifi_speed_mbps', models.IntegerField(blank=True, null=True)),
                ('amenities_json', models.JSONField(default=dict)),
                ('operating_hours_json', models.JSONField()),
                ('pricing_model', models.CharField(max_length=50)),
                ('active_flag', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'venue',
            },
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('space_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('space_name', models.CharField(max_length=255)),
                ('capacity', models.PositiveIntegerField()),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('daily_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('availability_status', models.CharField(choices=[('Available', 'Available'), ('Occupied', 'Occupied'), ('Maintenance', 'Maintenance')], default='Available', max_length=20)),
                ('space_amenities_json', models.JSONField(default=dict)),
                ('space_type_code', models.CharField(blank=True, choices=[('SharedDesk', 'Shared Desk'), ('PrivateRoom', 'Private Room'), ('Boardroom', 'Boardroom')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to='venues.venue')),
            ],
            options={
                'db_table': 'space',
            },
        ),
        migrations.AddIndex(
            model_name='venue',
            index=models.Index(fields=['venue_type_code'], name='venue_venue_t_4b6546_idx'),
        ),
        migrations.AddIndex(
            model_name='venue',
            index=models.Index(fields=['active_flag'], name='venue_active__254184_idx'),
        ),
    ]
